### ISSUE TITLE
hdr_black_floor_fix: roll off stopping point not working as expected anymore

### ISSUE THREAD

**Issue by EndlesslyFlowering** [EndlesslyFlowering/ReShade_HDR_shaders#34]
**Greetings,**

Is the _'roll off stopping point'_ in black floor lowering shader's functionality altered?
In earlier versions, the default value was '10.0nits' I'd loved using it on 1.0nit. It would work brilliantly.
But now with newer version of this shader, if I choose 1.0 or 10.0nits the screen goes completely dark?
I have to now use either 1000.0nits or 10000.0nits why is that?

A brief explanation will help a lot on how to use it properly.

**Thanks!**
@EndlesslyFlowering

_Originally posted by @ABDX80 in https://github.com/EndlesslyFlowering/ReShade_HDR_shaders/issues/10#issuecomment-2253750676_

**Comment by EndlesslyFlowering** [comment]
I can't replicate this in HDR10 or scRGB.
I also checked the code and everything is fine...

**Comment by ABDX80** [comment]
I just tried it with a fresh download of the latest repo as suggested, same issue persisted.

Anyhow, I was able to pinpoint the culprit.
This problem only happens when you use _'roll off stopping point'_ in conjunction with _'SDR Black Floor Emulation'_ enabled, specifically when _'processing color space'_ is set to **'BT.2020'**, this does not cause a problem if it is set to **'BT.709'** or **'DCI-P3'** presets.

So please try it this way, I'm sure it's going to be evident.
@EndlesslyFlowering

**Comment by EndlesslyFlowering** [comment]
> I just tried it with a fresh download of the latest repo as suggested, same issue persisted.
> 
> Anyhow, I was able to pinpoint the culprit. This problem only happens when you use _'roll off stopping point'_ in conjunction with _'SDR Black Floor Emulation'_ enabled, specifically when _'processing color space'_ is set to **'BT.2020'**, this does not cause a problem if it is set to **'BT.709'** or **'DCI-P3'** presets.
> 
> So please try it this way, I'm sure it's going to be evident. @EndlesslyFlowering

OK, that got me on the right track. Thank You!

fix until next release:
[hdr_black_floor_fix.zip](https://github.com/user-attachments/files/17194803/hdr_black_floor_fix.zip)
goes into folder `lilium__include`

**Comment by EndlesslyFlowering** [comment]
fixed with dcdd9ce7819978341364771b8c7d37d00f5e4e49
